///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace CalTestRanorex
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the CalTestRanorexRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    [RepositoryFolder("847916f2-d09b-4982-8bd0-0f9705ffa9e1")]
    public partial class CalTestRanorexRepository : RepoGenBaseFolder
    {
        static CalTestRanorexRepository instance = new CalTestRanorexRepository();

        /// <summary>
        /// Gets the singleton class instance representing the CalTestRanorexRepository element repository.
        /// </summary>
        [RepositoryFolder("847916f2-d09b-4982-8bd0-0f9705ffa9e1")]
        public static CalTestRanorexRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public CalTestRanorexRepository() 
            : base("CalTestRanorexRepository", "/", null, 0, false, "847916f2-d09b-4982-8bd0-0f9705ffa9e1", ".\\RepositoryImages\\CalTestRanorexRepository847916f2.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("847916f2-d09b-4982-8bd0-0f9705ffa9e1")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "6.0")]
    public partial class CalTestRanorexRepositoryFolders
    {
    }
#pragma warning restore 0436
}